Toneys branch
tcoleman1/Team5 pull request #23
Opened 2019-09-10 01:26 UTC by toneyhiggins2

Fixing modal background image

2019-09-10 18:02 UTC, tcoleman1 approved these changes

2019-09-10 18:10 UTC, tcoleman1 requested changes
Breaking the loading of google maps & event handling functionality.

2019-09-11 13:34 UTC, jastring1 approved these changes

2019-09-11 13:35 UTC, jastring1 approved these changes

2019-09-11 16:06 UTC, closed without merging